src/PersonalPlanner.jsx

- Modified File: `src/PersonalPlanner.jsx`
- Modified the import for Navbar

update to navbar import

---

tailwind.config.js

added tailwind config

---

src/components/auth/Login.jsx
src/components/auth/Register.jsx
src/components/nav/NavBar.jsx
src/pages/Profile.jsx
src/views/ApplicationViews.jsx
src/views/Authorized.jsx

added login and registration functionality in need of work.

added some work in progress login

---

src/PersonalPlanner.jsx
src/components/nav/NavBar.jsx
src/pages/Profile.jsx
src/views/ApplicationViews.jsx
src/views/Authorized.jsx

Added functionality for login and register. When a user is starting the app they will see the home page and calendar: We have added the functionality so a user can click register button and create an account , also a user can login.

added login register

---

src/components/nav/NavBar.jsx
src/pages/Home.jsx

Fixed the css for calendar and made the navbar more legible. Still working on final touches but this is a good stopping point

fixed some css

---

src/components/auth/Login.jsx

In the login.js we have included the entirety of the user data in the current_user json string.

added user info in application

---

src/components/nav/NavBar.jsx
src/pages/Calendar.jsx
src/pages/Home.jsx
src/pages/Weather.jsx
src/views/ApplicationViews.jsx

- modified:   src/components/nav/NavBar.jsx
- new file:   src/pages/Calendar.jsx
- modified:   src/pages/Home.jsx
- new file:   src/pages/Weather.jsx
- modified:   src/views/ApplicationViews.jsx
Added new routes, pages for Weather and Calendar Navbar component to `PersonalPlanner.jsx`:

refactor to add working links to navbar

---

src/pages/Profile.jsx

Inside of the profile.js page we have the code allowing for the users basic info to display. eventually events and the current_users events will be available but this functionality is not there yet,

added some basic profile page info with limited styling

---

src/components/forms/EventForm.jsx
src/pages/Calendar.jsx
src/views/ApplicationViews.jsx

- `src/pages/Calendar.jsx`
- `src/views/ApplicationViews.jsx`
- `src/components/forms/EventForm.jsx`
- Added `CurrentUser` to the route for enhanced user tracking.
- Updated with a "Create an Event" button.
- Implemented logic to check if a user is logged in or not.
- Created `EventForm.jsx` as a basic landing page for the "Create an Event" button.

refactor of calendar to add create event button and logic

---

index.html
src/components/auth/Register.jsx
src/pages/Calendar.jsx
src/pages/Profile.jsx
tailwind.config.js

Some work done on profile page and in the index html which provides a colored background.

added some profile page work

---

src/components/calendar/Calendar.jsx

- `src/components/calendar/Calendar.jsx`
Added a "Create Event" button to the Calendar component along with the necessary logic to handle event creation. This enhancement aims to improve the user experience by providing a convenient way to add new events directly from the calendar view.
- Implemented the "Create Event" button.
- Added logic to handle event creation based on user interactions.
- Added logic to direct logged in users and non logged in users.

add create event button and logic to calendar

---

.gitignore
src/pages/Weather.jsx
src/views/ApplicationViews.jsx

- `src/pages/Weather.jsx`
- `src/views/ApplicationViews.jsx`
This pull request refactors the Weather component to improve future forecast display:
1. **Refactor Weather Component:**
- Updated `Weather.jsx` to enhance the display of future forecast information.
- Improved readability and maintainability of the code.
2. **Update Application Views:**
- Modified `ApplicationViews.jsx` to ensure proper integration of the updated Weather component.
Changes made:
- Enhanced the structure and styling of future forecast display.
- Optimized code for better performance and scalability.

refactor of weather for future forecast display

---

src/components/forms/EventForm.jsx
src/managers/EventManager.jsx

Ability to create an event with the newly changed backend is now available **To Test** git fetch this branch and begin looking in `eventform.jsx` 
- we have all of the necessary fields in our component including the use effect bringing in the categories in a select field. also utilizing built in widgets for time and date. be sure to make sure the backend is correctly getting a 201 ok upon event form button click. for now it just returnes the created event object of fields and values.

created events

---

src/pages/Weather.jsx

- `src/pages/Weather.jsx`
This pull request refactors the display of weather data fetched from an API in the `Weather.jsx` file. Changes include:
1. **Improved Weather Display:**
- Updated the display logic to enhance the presentation of weather information on the page.
2. **Code Refactoring:**
- Refactored the code for better readability and maintainability, ensuring adherence to best practices.
- insert your OpenWeather key to pull forecast.

refactor to display of weather from API

---

src/managers/EventManager.jsx
src/pages/EventDetails.jsx
src/services/categoryService.jsx

added a `eventdetails delete and edit functionality. both are tested and working currently. I used a large amount of useState to capture the value of current selections and allow input OnChanges with complete and robust functionality for a good user experience when editing their event. To see the changes look in the categories.jsx , eventManager.jsx, and the eventdetails,jsx for the additions. 
**To TEST** follow procedure outlined and be sure to check network requests for 204 on delete and 200 on put

added edit update to event

---

src/pages/Profile.jsx
src/pages/Weather.jsx
src/services/eventsService.jsx
src/views/ApplicationViews.jsx

- `src/pages/Profile.jsx`
- `src/pages/Weather.jsx`
- `src/views/ApplicationViews.jsx`
- `src/services/eventsService.jsx`
This pull request focuses on enhancing the Profile page to connect with Event details:
1. **Profile Page Refactor:**
- Modified `Profile.jsx` to integrate with Event details for a more comprehensive user profile experience.
- Added list of events that the user has created with link to detail page
2. **Weather Page Update:**
- Made necessary adjustments in `Weather.jsx` to display 5 day weather forecast with drop down feature.
3. **Application Views Update:**
- Updated `ApplicationViews.jsx` to accommodate the changes related to the Profile page and Event details integration.
4. **New Service File:**
- Added `eventsService.jsx` to fetch events from backend API.

refactor to connect Profile to Events Details

---

src/components/calendar/CalendarDaysData.jsx

- `src/components/calendar/CalendarDaysData.jsx`
This pull request focuses on refactoring the `CalendarDaysData` component to facilitate the passing of events into the Calendar:
1. **CalendarDaysData Refactor:**
- Modified `CalendarDaysData.jsx` to enhance its functionality for passing events into the Calendar component.

refactor of CalendarDaysData to pass events into Calendar

---

src/components/calendar/Calendar.jsx
src/components/calendar/CategoryFilter.jsx

- `src/components/calendar/Calendar.jsx`
- `src/components/calendar/CategoryFilter.jsx`
This pull request aims to refactor the input fields in the Calendar and CategoryFilter components by adding `name` and `id` attributes:
1. **Calendar Component:**
- Added `name` and `id` attributes to input fields in `Calendar.jsx` for improved accessibility and form submission handling.
2. **CategoryFilter Component:**
- Similarly, enhanced the input fields in `CategoryFilter.jsx` with `name` and `id` attributes to ensure consistency and maintainability across components.

refactor to add name,id to input fields

---

src/components/calendar/CalendarDaysData.jsx

- `src/components/calendar/CalendarDaysData.jsx`
This pull request addresses the following changes:
- Refactored the link in `CalendarDaysData.jsx` to direct to the `EventDetails` page, enhancing the user experience and navigation within the application.

refactor CalendarDaysdata link to EventDetails

---

src/components/calendar/CalendarDaysData.jsx

- `src/components/calendar/CalendarDaysData.jsx`
This pull request standardizes the display format of event times in the `CalendarDaysData` component. By ensuring a consistent format, it improves clarity and user experience when viewing event times throughout the application.
- Verify that the changes do not affect any existing functionality and that the time formatting behaves as expected across different scenarios.

refactor of event_time to standard

---

src/pages/Weather.jsx

This pull request aims to refactor the styling to enhance the display of weather information on the application.
- **src/pages/Weather.jsx**: Refactored styling to improve the layout and presentation of weather data.
- Added new CSS classes for better alignment and spacing.
- Adjusted font sizes and colors for improved readability.
- Updated layout to ensure consistent display across different screen sizes.
Please review the changes and ensure:
- The weather information is displayed accurately and prominently.
- The styling changes do not introduce any regressions or layout issues.
- The application remains responsive and functional across various devices.
This update aims to provide a more visually appealing and user-friendly experience when viewing weather information within the …

refactor styling to display weather

---

src/managers/EventManager.jsx
src/pages/EventDetails.jsx
src/views/ApplicationViews.jsx

Added RSVP functionality to the frontend so that a user can at least RSVP and Connect to an event. Still not done with UI frontend,

added rsvp to details

---

src/managers/EventManager.jsx
src/pages/Profile.jsx

**to test** go to main and `git fetch` checkout into this branch and check changes. 
-`in the profile.jsx we have added a new fetch and are rendering the events that the current user has created only.

added unique event for profile

---

src/pages/Home.jsx

- Updated the text content in `Home.jsx` for clarity and conciseness.
- Adjusted the text color to enhance readability and visual appeal.
- The modifications aim to improve the presentation of information on the Home page.
- By refining the text and color, the goal is to create a more engaging and user-friendly experience for visitors.
- Feedback on the changes is welcome to ensure they align with the intended design and messaging.

update to Home page text

---

src/components/nav/NavBar.jsx

- Restored the hover effect in the navigation bar by updating the `NavBar.jsx` component.
- Reintroduced the hover functionality to enhance user interaction and visual feedback.
- The hover effect contributes to the overall usability and aesthetics of the navigation bar.

add navbar hover effect back to updates

---

src/components/calendar/Calendar.jsx
src/components/calendar/CalendarDaysData.jsx
src/components/calendar/CategoryFilter.jsx
src/managers/EventManager.jsx

Check the calendar files for changes regarding a new backend Action decorator for getting fetches based on the category if selected. --Also refer to backend for changes. **GIT FETCH** this branch from main `git fetch` procedure

added calendar category filter

---

src/components/calendar/Calendar.css
src/pages/EventDetails.jsx

Added some needed styling, and conditional rendering for buttons in `eventdetails.jsx` page

added styling: and button conditions

---

src/pages/Profile.jsx

- Updated the styling of the Profile page to improve its visual appeal and user experience.
- Made adjustments to layout, colors, and fonts for better readability and consistency.

refactor Profile page styling

---

src/components/forms/EventForm.jsx

- Refactored the events form component to update the text color for better visibility and aesthetics.
- Adjusted the styling to enhance the overall user experience and ensure consistency with the application's design.
- Tested the form functionality to confirm that the changes did not affect its behavior.
- Reviewed the code to ensure clarity and maintainability.

refactor of events form with updated text color

---

src/pages/Home.jsx

- Added a new Features section to the Home page.
- Incorporated bullet points to list out the app features.
- Ensured the bullet points are left-aligned with the feature text for better readability.
- Styled the Features section to match the existing design theme of the app.
- Updated the Home page content to include information about the app features.

refactor Home with Features section

---

src/pages/Profile.jsx

- Modified the Profile component (src/pages/Profile.jsx) to retrieve and display currentUser information.
- Updated the UI to present the currentUser info in a clear and user-friendly manner.
- Add Edit button, non functional, to profile.

update to Profile page to display currentUser info

---

src/managers/userService.jsx
src/pages/Profile.jsx
tailwind.config.js

Refactor for Edit of PPUser
1. Modified `userService.jsx`:
- Updated functionality to support editing `PPUser`.
- Added a delete function to be completed.
2. Modified `Profile.jsx`:
- Adjustments made to accommodate changes related to editing `PPUser`.
3. Modified `tailwind.config.js`:
- Made necessary modifications for the refactor.
- added red to use with delete functions

refactor for edit of PPuser

---

src/components/calendar/Calendar.css
src/components/calendar/Calendar.jsx

Added show all button with simple window re render.

show all button

---

src/pages/Home.jsx
src/pages/Profile.jsx

1. Modified `src/pages/Home.jsx`.
- Refactored the home page layout to enhance responsiveness for mobile devices.
2. Modified `src/pages/Profile.jsx`.
- Refactored the profile page layout to improve the mobile view.
These changes aim to provide a better user experience for users accessing the application from mobile devices.

refactor of home and profile for mobile view

---

src/pages/Profile.jsx

1. Modified `src/pages/Profile.jsx`.
- Added the handleSubmit function to handle form submissions.
This change aims to restore functionality to the Profile page by reintroducing the handleSubmit function.

add handlesubmit back into project

---

src/pages/Home.jsx
src/pages/Profile.jsx

1. Modified `src/pages/Home.jsx` and `src/pages/Profile.jsx`.
- Implemented responsive design changes to improve the layout and adaptability of the Home and Profile pages for various screen sizes.
These changes aim to enhance the user experience by ensuring that the application is visually appealing and functional across different devices and screen resolutions.

refactor for responsive design

---

src/components/calendar/Calendar.jsx
src/components/calendar/Ifmobile.css

_To Test_ git checkout into this branch and look for the `Ifmobile.css` where we are conditionally rendering css based upon the width of the device with `@media@` . Adjusting multiple vanilla css values got this page to display the way we want to dependent upon those sizes that are less wide than 768 px

added ifMobile for calendar

---

src/pages/Weather.jsx

1. Modified the `src/pages/Weather.jsx` file to optimize the layout and styling for various screen resolutions.
2. Made adjustments to the CSS classes and styles to enhance the appearance and usability of the weather component on smaller devices.
3. Improved the overall user experience by ensuring that weather information is displayed appropriately regardless of the device used.

Mjt responsiveweather

---

src/pages/Profile.jsx

**Description:**
This pull request addresses the need to refactor the codebase to include functionality for deleting a user. The changes primarily focus on the `Profile.jsx` file.
**Changes Made:**
- Modified `src/pages/Profile.jsx` to include the delete user functionality.
**Testing Done:**
- [ X ] Tested the delete user functionality thoroughly.
- [ X ] Ensured that the user experience remains smooth after the refactor.
- [ X ] Verified the compatibility of changes across different devices and browsers.

refactor including delete user functionality

---

src/components/auth/Login.jsx
src/components/auth/Register.jsx

In the login.jsx I have added the Registration wording instead of "Cancel" 
-`register.jsx` added in the useState for registration to keep a setregister function that will be used to automatically fetch the user information and login the user automatically when the user registers successfully.

added register re route

---

index.html
src/index.css

**Description:**
This pull request introduces an animation for the body of the application to enhance its visual appeal and user experience. The changes primarily involve modifications to `index.html` and `src/index.css` files.
**Changes Made:**
- Modified `index.html` and `src/index.css` to implement the animation for the body.
- 48 insertions were made to achieve this enhancement.
**Branch Information:**
- Created a new branch named `mjt-bodysparkle` based on the main branch.
- Pushed commits to the `mjt-bodysparkle` branch.

create animation for body

---

index.html
src/index.css

**Description:**
This pull request aims to improve the sparkle effect animation in the application for a more visually appealing and engaging user experience. The changes involve refactoring `index.html` and `src/index.css` to enhance the animation quality.
**Changes Made:**
- Refactored `index.html` and `src/index.css` to create a better sparkle effect animation.
- 75 insertions and 79 deletions were made to achieve this improvement.
- `index.html` was rewritten (94%).
- `src/index.css` was rewritten (81%).

refactor to create better sparkle effect animation

---

index.html
src/index.css

Inside of `index.css` and `index.html` added changes into these files to change star vectors and locations while adding in fontawesome pictures.

added stars

---

src/managers/AuthManager.js
src/managers/CategoryManager.jsx
src/managers/EventManager.jsx
src/managers/userService.jsx
src/pages/Profile.jsx

added new fetch endpoint for all https://personal-planner-hryyx.ondigitalocean.app/

changed fetch
